-- liquibase formatted sql

-- changeset victor:1_drop_objects endDelimiter:/
-- comment: Drop existing database objects if necessary
DECLARE
  v_drop BOOLEAN := TRUE; -- Set to FALSE to skip dropping existing objects
BEGIN
  IF v_drop THEN
    -- Drops in reverse order (dependencies first)
    BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_interactions_tenant_time'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE interactions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE memory_kv CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE memory_long CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_messages_conv_created'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE messages CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE conversations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END IF;
END;
/
-- rollback SELECT 1 FROM DUAL;

-- changeset victor:2_create_conversations_table
CREATE TABLE conversations (
  conversation_id   VARCHAR2(64) PRIMARY KEY,
  tenant_id         VARCHAR2(64) NOT NULL,
  user_id           VARCHAR2(128),
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status            VARCHAR2(32)
);
-- rollback DROP TABLE conversations;

-- changeset victor:3_create_messages_table
CREATE TABLE messages (
  message_id        VARCHAR2(64) PRIMARY KEY,
  conversation_id   VARCHAR2(64) NOT NULL,
  role              VARCHAR2(16) CHECK (role IN ('user','assistant','system')),
  content           CLOB,
  tokens_in         NUMBER,
  tokens_out        NUMBER,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_messages_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
);
-- rollback DROP TABLE messages;

-- changeset victor:4_create_messages_index
CREATE INDEX idx_messages_conv_created ON messages(conversation_id, created_at);
-- rollback DROP INDEX idx_messages_conv_created;

-- changeset victor:5_create_memory_long_table
CREATE TABLE memory_long (
  conversation_id   VARCHAR2(64) PRIMARY KEY,
  summary_text      CLOB,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_memory_long_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
);
-- rollback DROP TABLE memory_long;

-- changeset victor:6_create_memory_kv_table
CREATE TABLE memory_kv (
  conversation_id   VARCHAR2(64) NOT NULL,
  key               VARCHAR2(128) NOT NULL,
  value_json        JSON,
  ttl_ts            TIMESTAMP,
  CONSTRAINT pk_memory_kv PRIMARY KEY (conversation_id, key),
  CONSTRAINT fk_memory_kv_conversation
    FOREIGN KEY (conversation_id) REFERENCES conversations(conversation_id)
);
-- rollback DROP TABLE memory_kv;

-- changeset victor:7_create_interactions_table
CREATE TABLE interactions (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id         VARCHAR2(64),
  route             VARCHAR2(64),
  model_id          VARCHAR2(255),
  params_json       JSON,
  latency_ms        NUMBER,
  tokens_in         NUMBER,
  tokens_out        NUMBER,
  cost_est          NUMBER,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
-- rollback DROP TABLE interactions;

-- changeset victor:8_create_interactions_index
CREATE INDEX idx_interactions_tenant_time ON interactions(tenant_id, created_at);
-- rollback DROP INDEX idx_interactions_tenant_time;
